config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  scope "(:locale)", locale: /en|de/ do

    root "pokemon#index"

    resources :pokemon do
      get "search", on: :collection
    end

    devise_for :users, controllers: { profiles: "users/profiles" }

    namespace :users do
      get "profiles/show"
      get "profiles/edit"
    end
  end
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    validates_presence_of :name, :pokemon_type, :region
end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController
  before_action :set_pokemon, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  # GET
  def index
    @pokemon = Pokemon.where(search_params)
    @name = search_params[:name]
  end

  # GET
  def show
  end

  # GET
  def new
    @pokemon = Pokemon.new
  end

  # GET
  def edit
  end

  # POST
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: "Pokemon was successfully created." }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: "Pokemon was successfully updated." }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE 
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemon_index_url, notice: "Pokemon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @pokemon = Pokemon.where(search_params)
    @name = search_params[:name]

    @pokemon_types = Pokemon.distinct.pluck(:pokemon_type)
    @regions = Pokemon.distinct.pluck(:region)
  end

  private
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    def pokemon_params
      params
        .require(:pokemon)
        .permit(:name, :pokemon_type, :region)
    end

    def search_params
      params
        .permit(:name, :pokemon_type, :region)
        # Delete any passed params that are nil or empty string
        .delete_if {|key, value| value.blank? }
    end
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/views/pokemon/_back.html.haml
= link_to t(".back"), pokemon_index_path

app/views/pokemon/_form.html.erb
<%= form_with(url: pokemon_index_path, method: :post, model: pokemon) do |form| %>
  <% if pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
        <% pokemon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :pokemon_type %>
    <%= form.text_field :pokemon_type %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemon/_pokemon.html.erb
<tbody>
    <tr>
        <td><%= pokemon.name %></td>
        <td><%= pokemon.pokemon_type %></td>
        <td><%= pokemon.region %></td>
        <td>
          <%= link_to t(".show"), pokemon %>
          <%= link_to t(".edit"), edit_pokemon_path(pokemon) %>
          <%= link_to t(".destroy"), pokemon, method: :delete, data: { confirm: t(".destroy_confirmation") } %>
        </td>
    </tr>
</tbody>

app/views/pokemon/_pokemon.html.haml
%tbody
  %tr
    %td= pokemon.name
    %td= pokemon.pokemon_type
    %td= pokemon.region 
    %td= link_to t(".show"), pokemon_path(pokemon)
    %td= link_to t(".edit"), edit_pokemon_path(pokemon) 
    %td= link_to t(".destroy"), pokemon, method: :delete, data: { confirm: t(".destroy_confirmation") }

app/views/pokemon/edit.html.erb
<h1>Edit Pokemon</h1>

<%= render "form", pokemon: @pokemon %>

<%= link_to t(".show"), @pokemon %> |
<%= link_to "Back", :back %>

app/views/pokemon/edit.html.haml
%h1 Edit Pokemon

= render "form", pokemon: @pokemon

= link_to t(".show"), @pokemon
= render "back"

app/views/pokemon/index.html.erb
<h1>Pokemon</h1>

<p>
  <%= form_with url: "/pokemon", method: :get, local: true do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, :value => @name %>

    <%= f.submit t(".search") %>
  <% end %>

  <%= link_to t(".advanced_search"), search_pokemon_index_path %>
</p>

<p>
  <div class="tbl-container">
    <% if @pokemon.empty? %>
      <p>No Pokemon were found.</p>
    <% else %>
      <table class="table table-hover table-sm">
        <thead class="table-dark">
          <tr>
            <th style="width: 10%"><%= t(".name") %></th>
            <th style="width: 10%"><%= t(".type") %></th>
            <th style="width: 10%"><%= t(".region") %></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <%= render @pokemon %>
      </table>
    <% end %>
  </div>
</p>

<p>
  <%= link_to t(".clear_search"), pokemon_index_path %> |
  <%= link_to t(".new_pokemon"), new_pokemon_path %>
</p>

app/views/pokemon/index.html.haml
%p#notice= notice

%h1 Pokemon

= form_with url: pokemon_index_path, method: :get, local: true do |f|
  = f.label :name
  = f.text_field :name
  = f.submit t(".search")
= link_to t(".advanced_search"), search_pokemon_index_path
%br
%br

- if @pokemons.empty?
  %p No Pokemon were found.
- else
  %table
    %thead
      %tr
        %th= t(".name")
        %th= t(".type")
        %th= t(".region")
        %th{colspan: "3"}
    = render @pokemons
%br

= link_to t(".new_pokemon"), new_pokemon_path

app/views/pokemon/new.html.erb
<h1>New Pokemon</h1>

<%= render "form", pokemon: @pokemon %>

<%= link_to "Back", :back %>

app/views/pokemon/new.html.haml
%h1= t(".new_pokemon")

= render "form", pokemon: @pokemon
%br

= render "back"

app/views/pokemon/search.html.erb
<h1><%= t(".advanced_search") %></h1>

<p>
  <%= form_with(url: search_pokemon_index_path, method: :get) do |f| %>
    <%= f.label t(".name") %>
    <%= f.text_field :name, :value => @name %>
    <br>
    <%= f.label t(".type") %>
    <%= f.select :pokemon_type, options_for_select(@pokemon_types, params[:pokemon_type]), include_blank: true %>
    <br>
    <%= f.label t(".region") %>
    <%= f.select :region, options_for_select(@regions, params[:region]), include_blank: true %>
    <br>
    <%= f.submit t(".search") %>
  <% end %>
</p>

<p>
  <% if @pokemon.empty? %>
      <p>No Pokemon were found.</p>
  <% else %>
    <table class="table table-hover table-sm">
      <thead class="table-dark">
        <tr>
          <th style="width: 10%"><%= t(".name") %></th>
          <th style="width: 10%"><%= t(".type") %></th>
          <th style="width: 10%"><%= t(".region") %></th>
          <th colspan="3"></th>
        </tr>
      </thead>
        <%= render @pokemon %>
    </table>
  <% end %>
</p>

<p>
  <%= link_to "Back", :back %> |
  <%= link_to t(".clear_search"), search_pokemon_index_path %>
</p>

app/views/pokemon/search.html.haml
%h1= t(".advanced_search")

= form_with url: search_pokemon_index_path, method: :get do |f|

	= f.label :name
	= f.text_field :name

	= f.label :pokemon_type
	= f.select :pokemon_type, options_for_select(@pokemon_types, params[:pokemon_type]), include_blank: true

	= f.label :region
	= f.select :region, options_for_select(@regions, params[:region]), include_blank: true
	%br

	= f.submit t(".search")
	%br
	%br

- if @pokemons.empty?
	%p No Pokemon were found.
- else
	%table
		%thead
			%tr
				%th= t(".name")
				%th= t(".type")
				%th= t(".region")
				%th{colspan: "3"}
		= render @pokemons
%br

= render "back"

app/views/pokemon/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t(".name") %>:</strong>
  <%= @pokemon.name %>
</p>

<p>
  <strong><%= t(".type") %>:</strong>
  <%= @pokemon.pokemon_type %>
</p>

<p>
  <strong><%= t(".region") %>:</strong>
  <%= @pokemon.region %>
</p>

<%= link_to t(".edit"), edit_pokemon_path(@pokemon) %> |
<%= link_to "Back", :back %>

app/views/pokemon/show.html.haml
%p#notice= notice

%p
	%strong #{t(".name")}:
	= @pokemon.name

%p
	%strong #{t(".type")}:
	= @pokemon.pokemon_type

%p
	%strong #{t(".region")}:
	= @pokemon.region

= link_to t(".edit"), edit_pokemon_path(@pokemon)
= render "back"