config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  scope "(:locale)", locale: /en|de/ do

    root "pokemon#index"

    resources :pokemon do
      get "search", on: :collection
    end

    devise_for :users, controllers: { profiles: "users/profiles" }

    namespace :users do
      get "profiles/show"
      get "profiles/edit"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    around_action :switch_locale

    def switch_locale(&action)
        locale = params[:locale] || I18n.default_locale
        I18n.with_locale(locale, &action)
    end

    def default_url_options
        { locale: I18n.locale }
    end

    protected

      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) {
          |u| u.permit(:username, :email, :password)
        }
        devise_parameter_sanitizer.permit(:account_update) {
          |u| u.permit(:username, :email, :password, :current_password)
        }
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg bg-dark text-white">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <ul class="nav ms-4">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <img class="img">
            <%= image_tag("logos/pokeball.png", width: "32", height: "32") %>
          </img>
        </a>
      </ul>
      <!-- Navbar brand -->

      <!-- Left links -->
      <ul class="navbar-nav me-auto ms-2 mb-2 mb-lg-0">
        <li><a><%= link_to "Home", root_path, class: "nav-link px-2 text-secondary" %></a></li>
        <li><a><%= link_to "Advanced Search", search_pokemon_index_path, class: "nav-link px-2 text-white" %></a></li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center">
      <div class="text-end">
        <% if user_signed_in? %>
          <div class="container">
            <div class="dropdown d-inline-block" >
              <button class="btn btn-outline-light me-2 dropdown-toggle" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.username %>
              </button>
              <ul
                class="dropdown-menu"
                aria-labelledby="navbarDropdownMenuLink"
              >
              <li>
                <%= link_to "Profile", users_profiles_show_path, class: "dropdown-item ps-4" %>
              </li>
                <li>
                  <%= link_to "Edit Password", edit_user_registration_path, class: "dropdown-item ps-4" %>
                </li>
              </ul>
            </div>
            <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: "btn btn-danger" %>
          </div>
        <% else %>
          <div class="container">
            <%= link_to "Sign In", new_user_session_path, class: "btn btn-outline-light me-2" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-warning" %>
          </div>
        <% end %>
      </div>

      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
          Language
        </button>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuLink"
        >
        <li>
          <%= link_to "English", root_path(locale: :en), class: "dropdown-item ps-4" %>
        </li>
          <li>
            <%= link_to "Deutsch", root_path(locale: :de), class: "dropdown-item ps-4" %>
          </li>
        </ul>
      </div>

    </div>
    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->